Add draft BUILD files for the Bazel build system. Building with Bazel currently doesn't work, it results in this compile error:
INFO: Found 1 target...
ERROR: /home/marco/projects/fruit/BUILD:2:1: undeclared inclusion(s) in rule '//:fruit':
this rule is missing dependency declarations for the following files included by 'src/demangle_type_name.cpp':
  '/usr/lib64/gcc/x86_64-suse-linux/4.8/include/stdarg.h'
  '/usr/lib64/gcc/x86_64-suse-linux/4.8/include/stddef.h'
  '/usr/lib64/gcc/x86_64-suse-linux/4.8/include/stdint.h'.
Target //:fruit failed to build
INFO: Elapsed time: 0.808s, Critical Path: 0.38s

It's not clear if that's a Bazel issue or I'm missing something in the config.